### ISSUE TITLE
Auth0 + Alexa Tutorial - Payload Too Large

### ISSUE THREAD

**Issue by elmiratap** [auth0/wt-cli#191]
I am working through [this tutorial](https://auth0.com/blog/interaction-based-auth-for-alexa-with-auth0/), and at the 
`wt create -n pod --secrets-file src\runtimes\secrets.ini build\bundle.js` 
step, I get the following error: 
```
Uncaught error:  Request body size exceeds 122880
Error: Payload Too Large
    at Request.callback (/usr/local/lib/node_modules/wt-cli/node_modules/superagent/lib/node/index.js:696:15)
    at parser (/usr/local/lib/node_modules/wt-cli/node_modules/superagent/lib/node/index.js:906:18)
    at IncomingMessage.res.on (/usr/local/lib/node_modules/wt-cli/node_modules/superagent/lib/node/parsers/json.js:19:7)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:114:19)
Please report this at: https://github.com/auth0/wt-cli/issues
```
Do you have any suggestions for getting past this issue? It seems the tutorial worked for others in the past, but perhaps there's been a change to the codebase that requires a different approach.

**Comment by rwtombaugh** [comment]
Hi @elmiratap 

The error that you are hitting is because the bundled code file you have is too large. The tutorial in question is a little out of date and it doesn't reflect the better way to write your webtasks without bundling. 

Instead of bundling, use a `package.json` file and list your npm module dependencies in the package.json.  When you run `wt-cli create webtask-code-file.js` the wt-cli will read the package.json and provision all of the npm modules on the runtime for you. No bundling required. This will dramatically reduce the size of the webtask code and you will no longer hit the max size issue you currently are hitting.

**Comment by elmiratap** [comment]
Thank you @rwtombaugh!

**Comment by stevezau** [comment]
I also am having the same issue. The problem is when you run without bundle it does not include the local files so you need to bundle just the local files somehow??

https://github.com/auth0/auth0-alexa-authentication-sample/blob/master/src/runtimes/wrapper-webtask.js#L9-L21
