### ISSUE TITLE
--bundle flag causes issues when using node8 profile

### ISSUE THREAD

**Issue by BrighTide** [auth0/wt-cli#196]
Hi,

I'm getting "Compilation failed: regeneratorRuntime is not defined" when using the --bundle flag (to enable multiple files) in a project using node8 set up as per https://tomasz.janczuk.org/2017/09/auth0-webtasks-and-node-8.html

**Comment by NotMyself** [comment]
Hi @BrighTide,

Thanks for reaching out to us. Sorry that it took so long to respond to this issue. We have released several version of wt-cli since April. I just tried to reproduce this issue and was not able to recreate the error. I know where have fixed several bugs in the bundling command recently. Looks like it has been fixed.

I am going to close this issue. If you are still encountering the problem with the latest cli, please reopen.
