### ISSUE TITLE
useful if user can set env variable

### ISSUE THREAD

**Issue by coolicer** [auth0/wt-cli#26]
set env variable via wt-cli, but others can not see

**Comment by ggoodman** [comment]
We've looked at enabling this but it is something that is difficult from an architectural perspective. Multiple different 'webtasks' can run in the same container (node context). So it becomes tricky to decide which environment variables to set and when. Consider that any waiting on IO of multiple webtask executions in the same container can cause control to flip back and forth between 'webtasks'.

In order to prevent unexpected behaviour this is something we will not support for the time being.

**Comment by coolicer** [comment]
hope you can find a best way
