### ISSUE TITLE
CRON schedule formats for the rest of us

### ISSUE THREAD

**Issue by tjanczuk** [auth0/wt-cli#48]
It would be great to be able to say `5m` or `1h` as the `schedule` string for CRON.

**Comment by ggoodman** [comment]
It would be great. The biggest issue with this is that not all intervals can be mapped to cron schedules. You cannot, for example say `'run every 25 minutes'` because `25` is not a factor of `60` minutes. Cron schedules have no concept of intervals; everything must be anchored relative to `minute`, `hour`, `date`, `day of week` or `month` boundaries.

Any idea how we could find a middle ground?

**Comment by tjanczuk** [comment]
Even if we ship just a set of pre-canned settings it would be an improvement, e.g. `15m`, `30m`, `1h`, etc.    - you get the idea.

**Comment by ggoodman** [comment]
Resolved by 3b01a1b.
