### ISSUE TITLE
Add a `wt open [webtask-name]` to open webtask url in browser

### ISSUE THREAD

**Issue by cristiandouce** [auth0/wt-cli#80]
It'd be a useful feature for webtasks serving html.

**Comment by ggoodman** [comment]
@cristiandouce this does sound useful. Not sure if `open` is the right verb.

Do you want to submit a PR? It would mean creating a new command similar to [edit](https://github.com/auth0/wt-cli/blob/master/bin/edit.js) and then [registering](https://github.com/auth0/wt-cli/blob/master/bin/wt#L35) that command.

**Comment by cyhsutw** [comment]
Hi @cristiandouce @ggoodman 👋 ,

I would love to help to implement this feature. 
What do you think about using `run` as the verb?  

(Grabbed from: https://webtask.io/docs/api_run)

Would like to hear your feedback on this, thanks!

**Comment by ggoodman** [comment]
@cyhsutw I'm a bit reluctant to call it `run` because the reality is that many webtasks are designed for accepting non `GET` requests or have no meaningful output in the browser. So for most webtasks `wt run` would not meaningfully 'run' them.

May I instead suggest `wt browser <name>` or `wt browse <name>`?

Regardless, I wouldn't get hung-up on the naming. If you put together the PR, we'd be happy to review!

**Comment by cyhsutw** [comment]
@ggoodman Thanks for the input 😄  

I've opened a pull request #91, would love to have your feedback on that!
